import AboutContents from "@/Components/AboutContents";

export const metadata = {
    title: "About",
    keywords:['about','about','about page'],
    description: "Generated by create next app",
  };

const About = () => {
    return (
        <div>
                Hi, I am about page

                <AboutContents></AboutContents>
        </div>
    );
};

export default About;